### ISSUE TITLE
add selected elements of a list inside of tags

### ISSUE THREAD

**Issue by ertwro** [aca/emmet-ls#57]
if I have a list of elements. is there a way of adding them to an ordered list, such that each element is inside its own tag?

**Comment by olrtg** [comment]
Can you tell me the desired output? 🤔

**Comment by olrtg** [comment]
Interesting.. that seems to escape from my nvim knowledge but I'll investigate to see what I can do

**Comment by olrtg** [comment]
@ertwro now that I think of it I don't believe that something like this can exist (at least never seen) something like this done for a language server (a user command like `EmmetWrapInAbbreviation ol*`). Maybe with a little plugin or creating yourself an user command in your dotfiles you can achieve something like this.

The way I personally would approach this is recording a macro literally using the following inputs:
```
_vg_Stli>
```

Breaking it down is:
- `_` go to the first non-whitespace char in the line
- `v` start selection
- `g_` go to the last non-whitespace char in the line
- `St` (from `vim-surround`) to surround the current selection in a HTML/XML like tag
- `li>` the name of the tag and closing the tag with `>` since the input already starts with `<`

And the I would apply it to each line of the visual block selection like this:
```
'<,'>norm @q
```
(`q` is the letter on which I'd saved the macro)

Of course you can investigate how to save that macro globally so you can always use it without having to record the macro every time.

Let me know if that helps!

**Comment by ertwro** [comment]
I was trying to avoid installing another package by using the native expansion provided by emmet-ls. I created the following function but it wont expand and I'm afraid is becuase is related to the way the server expands the code:

```lua
local M = {}

function M.wrap_with_abbreviation(abbreviation)
  local bufnr = vim.api.nvim_get_current_buf()

  local start_line, _ = unpack(vim.api.nvim_buf_get_mark(bufnr, '<'))
  local end_line, _ = unpack(vim.api.nvim_buf_get_mark(bufnr, '>'))

  local selected_text = table.concat(vim.api.nvim_buf_get_lines(bufnr, start_line - 1, end_line, false), '\n')

  vim.lsp.buf_request(bufnr, "emmet/expandAbbreviation", {
    language = "html",
    abbreviation = abbreviation,
    text = selected_text,
  }, function(_, _, result)
    if result then
      -- Check if the result is a table and extract the first element as a string
      if type(result) == "table" then
        result = result[1]
      end

      -- Replace the selected text with the expanded abbreviation
      vim.api.nvim_buf_set_lines(bufnr, start_line - 1, end_line, false, vim.split(result, '\n'))
    else
      print("Failed to expand abbreviation")
    end
  end)
end

return M
```

**Comment by ertwro** [comment]
I'm so sorry. I figure that your job as a dev is very hard to be paying attention to my requests. Thank you for your time and for the awesome service you provide.
