### ISSUE TITLE
emmet-ls not working in PHP

### ISSUE THREAD

**Issue by Tyson453** [aca/emmet-ls#73]
Hello everyone. I'm having trouble getting the emmet-ls server to run on my php files.

I'm using Lunarvim and have tried various ways to configure emmet-ls and it works in my html files, but when I try to add "php" to the filetypes table in my config, it doesn't work in my php files.

I'm working in Laravel so they are .blade.php files but other language servers say they are meant for php and still work on .blade.php so I assume it doesn't matter.

Any help would be greatly appreciated.

EDIT: This is what I get when running ":LspInfo" :
![Screenshot 2024-01-24 at 9 11 15 AM](https://github.com/aca/emmet-ls/assets/95186148/f636e1c6-e1f9-42b9-804e-83ea219fdf55)

Here is where I'm setting it up in my config (taken from somewhere on the internet):
![Screenshot 2024-01-24 at 9 13 38 AM](https://github.com/aca/emmet-ls/assets/95186148/587110ed-b3e4-4e50-bfb0-9b2cd85dbd0c)

**Comment by cpmsmith** [comment]
In your `:LspInfo` output, you can see that `emmet_ls`' `filetypes` list doesn't match the `filetypes` list you provided in your config, so your config isn't applying. It looks like you're only mutating the default config `if not lspconfig.emmet_ls`, but `lspconfig` supports `emmet_ls`, so that property exists, so lines 30–48 will never run.

I'm not sure if there's some intent behind providing the filetypes as a fallback default config for `emmet_ls` instead of just providing them to the `setup` call, or if LunarVim changes how this is done, but providing it to the `setup` call like so definitely works:

```lua
lspconfig.emmet_ls.setup({
	capabilities = capabilities,
	filetypes = {
		'html',
		'css',
		-- […]
		'php',
	},
})
```

**Comment by Tyson453** [comment]
I could've sworn I tried this already. I even have a file with that sort of structure in it. I guess I didn't fully save or reset properly before but it worked. Thank you.

**Comment by Tyson453** [comment]
I could've sworn I tried this already. I even have a file with that sort of structure in it. I guess I didn't fully save or reset properly before but it worked. Thank you.

**Comment by ahmadxgani** [comment]
is it possible to add new file type to lspconfig? so detected file type is blade instead of php

I'm sorry if this isn't a proper place to ask that question but maybe you know something about it?

**Comment by end3r-man** [comment]
> is it possible to add new file type to lspconfig? so detected file type is blade instead of php
> 
> I'm sorry if this isn't a proper place to ask that question but maybe you know something about it?

any possible solution found??

**Comment by mCassy** [comment]
Try adding "blade" to filetypes i.e 

```lua
filetypes = {
    "css",
    ...
    "blade",					},
}
```
